# Generated by Django 3.2.6 on 2021-09-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lession',
            name='tab',
        ),
        migrations.AddField(
            model_name='question',
            name='lession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lession'),
        ),
        migrations.AddField(
            model_name='question',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tab'),
        ),
    ]
