# Generated by Django 3.2.6 on 2021-10-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='lession',
        ),
        migrations.AddField(
            model_name='question',
            name='lession',
            field=models.ManyToManyField(to='main.Lession'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='tab',
        ),
        migrations.AddField(
            model_name='question',
            name='tab',
            field=models.ManyToManyField(to='main.Tab'),
        ),
    ]
