# Generated by Django 3.2.6 on 2021-09-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210902_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.lession'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tab'),
        ),
    ]
